---
title: "Daily Exercise 20"
author: "Justin Singh-Mohudpur"
output: 
  html_document:
    code_folding: hide
    theme: sandstone
---
```{r setup, include = FALSE}
# Libraries
library(tidyverse)
library(sf)
library(climateR)
library(raster)
```

```{r, warning = FALSE, message = FALSE}
# Climate Variables
params <- c("palmer", "water_deficit", "soilm", "prcp")

# Area of Interest
AOI <- USAboundaries::us_states() %>%
    filter(state_name == "Iowa")

iowa <- climateR::getTerraClim(
    AOI,
    params,
    startDate = "2012-10-01"
) %>%
    stack() %>%
    setNames(params)

plot(stack(iowa$palmer, iowa$water_deficit, iowa$soilm, iowa$prcp), axes = FALSE, box=FALSE)

indices <- which(!is.na(getValues(iowa)))

kmeans_iowa <- iowa %>%
    getValues() %>%
    na.omit() %>%
    scale() %>%
    kmeans(9)

iowa_raster <- iowa$palmer
iowa_raster[indices] <- kmeans_iowa$cluster

plot(iowa_raster, col = blues9, axes = FALSE, box=FALSE, main = "k-means Clustering with k = 9")
```
