---
title: "Daily Exercise 13"
author: "Justin Singh-Mohudpur"
output: 
  html_document:
    code_folding: hide
    theme: sandstone
---

```{r setup, warning=FALSE, message=FALSE, include=FALSE}
library(tidyverse)
library(sf)
library(USAboundaries)
library(rmapshaper)
library(ggplot2)

theme_map <- function(...) {
  theme_minimal() +
    theme(
      text = element_text(family = "Ubuntu", color = "#22211d"),
      axis.line = element_blank(),
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      #panel.grid.minor = element_line(color = "#ebebe5", size = 0.2),
      #panel.grid.major = element_line(color = "#ebebe5", size = 0.2),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      # plot.background = element_rect(fill = "#f5f5f2", color = NA),
      plot.background = element_blank(),
      plot.title = element_text(hjust = 0.5, color = "#4e4d47", size = 16),
      # panel.background = element_rect(fill = "#f5f5f2", color = NA),
      panel.background = element_blank(),
      legend.background = element_rect(fill = "#f5f5f2", color = NA),
      panel.border = element_blank(),
      ...
    )
}
```

```{r, warning=FALSE, message=FALSE}
USAboundaries::us_states() %>%
  filter(!stusps %in% c("AK", "HI", "PR")) %>%
  st_transform(5070) %>%
  st_combine() ->
  conus

stConus <- st_simplify(conus, dTolerance = 55000)
msConus <- ms_simplify(conus, keep = 0.05)

ggplot() +
  geom_sf(data = conus) +
  theme_map() +
  labs(title = paste("Number of points: ", mapview::npts(conus)),
       caption = "Raw data")

ggplot() +
  geom_sf(data = stConus) +
  theme_map() +
  labs(title = paste("Number of points: ", mapview::npts(stConus)),
       caption = "Using st_simplify()")

ggplot() +
  geom_sf(data = msConus) +
  theme_map() + 
  labs(title = paste("Number of points: ", mapview::npts(msConus)),
       caption = "Using ms_simplify()")
```
